# Generated by Django 3.2.8 on 2021-10-12 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='short_content',
        ),
    ]
