# Generated by Django 3.2.8 on 2021-10-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_remove_article_short_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='short_content',
            field=models.CharField(blank=True, max_length=300, verbose_name='Краткое описание'),
        ),
    ]
