# Generated by Django 3.2.8 on 2021-10-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_article_short_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='short_content',
            field=models.CharField(default='Нет описания', max_length=300, verbose_name='Краткое описание'),
        ),
    ]
