# Generated by Django 3.2.8 on 2021-10-12 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_alter_article_short_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rewiews',
            new_name='Reviews',
        ),
    ]
